from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timedelta

RATING_FACTORS = {
    "easy": 1.8,
    "with_effort": 1.25,
    "hard": 0.8,
    "skip": 0.35,
}

RATING_SCORE = {"easy": 5, "with_effort": 3, "hard": 2, "skip": 1}


@dataclass
class ScheduleResult:
    interval_days: float
    next_review_at: str
    ease_factor: float
    retention: float


@dataclass
class NewUnitAllocation:
    review_minutes: float
    free_minutes: float
    suggested_new_units: int
    review_only: bool


@dataclass
class GuardrailRecommendation:
    recommended_new_units: int
    limiting_day: int | None
    limiting_projected_minutes: float
    horizon_days: int


def compute_next(unit_row, rating: str, now: datetime) -> ScheduleResult:
    prev_interval = float(unit_row["interval_days"] or 0)
    ef = float(unit_row["ease_factor"] or 2.5)
    review_count = int(unit_row["review_count"] or 0)

    if review_count == 0:
        interval = {"easy": 3, "with_effort": 1, "hard": 0.5, "skip": 0.2}[rating]
    else:
        interval = max(0.2, prev_interval * RATING_FACTORS[rating] * (ef / 2.5))

    ef = min(3.0, max(1.3, ef + (RATING_SCORE[rating] - 3) * 0.08))
    next_review = now + timedelta(days=interval)
    retention = retention_estimate(unit_row, now)
    return ScheduleResult(interval_days=interval, next_review_at=next_review.isoformat(timespec="seconds"), ease_factor=ef, retention=retention)


def retention_estimate(unit_row, now: datetime) -> float:
    last = unit_row["last_review_at"]
    if not last:
        return 0.15
    last_dt = datetime.fromisoformat(last)
    elapsed_days = max(0.0, (now - last_dt).total_seconds() / 86400)
    interval = float(unit_row["interval_days"] or 1)
    score = pow(2.71828, -elapsed_days / max(0.3, interval))
    return max(0.01, min(0.99, score))


def choose_new_units_allowed(due_count: int, daily_minutes: int, avg_review_seconds: float) -> bool:
    due_cost = due_count * max(avg_review_seconds, 45) / 60
    projected = due_cost * 1.3
    return projected < daily_minutes * 0.85


def allocate_new_units(
    due_review_minutes: float,
    daily_minutes: int,
    avg_new_unit_seconds: float,
    new_units_cap: int,
) -> NewUnitAllocation:
    review_minutes = max(0.0, float(due_review_minutes))
    session_minutes = max(0.0, float(daily_minutes))
    free_minutes = max(0.0, session_minutes - review_minutes)

    safe_new_unit_seconds = max(1.0, float(avg_new_unit_seconds))
    max_by_time = int((free_minutes * 60.0) // safe_new_unit_seconds)
    suggested_new_units = max(0, min(int(new_units_cap), max_by_time))

    return NewUnitAllocation(
        review_minutes=review_minutes,
        free_minutes=free_minutes,
        suggested_new_units=suggested_new_units,
        review_only=suggested_new_units == 0,
    )


def _new_unit_touch_weight(day: int) -> float:
    # Approximate expected review touches generated by new learning today.
    # Stronger recalls on day 1 and day 3, with lighter follow-ups afterwards.
    if day == 1:
        return 1.0
    if day == 2:
        return 0.35
    if day == 3:
        return 0.8
    if day <= 7:
        return 0.25
    if day <= 14:
        return 0.15
    return 0.1


def recommend_new_units_with_guardrail(
    due_review_minutes: float,
    daily_minutes: int,
    avg_new_unit_seconds: float,
    new_units_cap: int,
    horizon_days: int = 10,
    safety_threshold: float = 0.9,
) -> GuardrailRecommendation:
    allocation = allocate_new_units(due_review_minutes, daily_minutes, avg_new_unit_seconds, new_units_cap)
    time_budget_limit = allocation.suggested_new_units
    session_minutes = max(0.0, float(daily_minutes))
    budget_threshold = session_minutes * max(0.1, min(1.0, float(safety_threshold)))
    avg_new_minutes = max(1.0, float(avg_new_unit_seconds)) / 60.0
    baseline_future_minutes = max(0.0, float(due_review_minutes)) * 0.35

    best = 0
    limiting_day: int | None = None
    limiting_projected = 0.0
    for candidate in range(0, time_budget_limit + 1):
        safe = True
        for day in range(1, max(1, int(horizon_days)) + 1):
            baseline = max(0.0, float(due_review_minutes)) if day == 1 else baseline_future_minutes
            projected = baseline + (candidate * avg_new_minutes * _new_unit_touch_weight(day))
            if projected > budget_threshold:
                safe = False
                limiting_day = day
                limiting_projected = projected
                break
        if safe:
            best = candidate
        else:
            break

    return GuardrailRecommendation(
        recommended_new_units=best,
        limiting_day=limiting_day,
        limiting_projected_minutes=limiting_projected,
        horizon_days=max(1, int(horizon_days)),
    )
